[package]
name = "mj"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0"

[dependencies]
ractor = "0.10"
reqwest = { version = "0.12", features = ["default", "json", "gzip", "brotli", "stream"] }
html5ever = "0.27"
clap = { version = "4.5.17", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = "0.7"
markup5ever = "0.13.0"
hashbrown = "0.14.5"
url = "2.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
futures = "0.3"
