[package]
name = "mj_dom"
version = "0.1.0"
edition = "2021"

[dependencies]
html5ever = { workspace = true }
stakker = { workspace = true }
taffy = { workspace = true }
tracing = { workspace = true }
slotmap = { workspace = true } 
