[package]
name = "mj_layout"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mj_dom.path = "../mj_dom/"
mj_utilities.path = "../mj_utilities/"
stakker.workspace = true

[lints]
workspace = true
